### ISSUE TITLE
Bug in adding control bounds

### ISSUE THREAD

**Issue by nrkumar93** [aykutonol/cito#1]
Thanks for the library. In [line 221](https://github.com/aykutonol/cito/blob/master/src/cito/sqopt.cpp#L221) of `sqopt.cpp`, should the check not be 

```
if (isAFree[j] == 0)
```
instead of
```
if (isAFree == 0)
```
?

**Comment by aykutonol** [comment]
@nrkumar93, that's exactly right. This is indeed a critical bug since it was, apparently, causing actuator limitations to be ignored. It's now fixed in the `devel` and `master` branches. Thank you so much!
